version: "3.8"

services:
  application:
    image: test
    container_name: test
    build:
      context: .
      dockerfile: ./dockerfile
    ports:
      - 4000:4000
      - 9228:9228
    volumes:
      - ./:/app:rw
    command: ["yarn", "dev"]
    healthcheck:
      test: curl --fail http://localhost || exit 1
      interval: 60s
      timeout: 30s
      retries: 5
      start_period: 40s
    env_file:
      - .env
