name: Night Web API APP Build
on: 
    pull_request: 
        branches: [master]
        types: [ opened, reopened, synchronize ]

jobs:
    
    pr_notifier:
      name: PR Notification
      runs-on: ubuntu-latest
      steps:
        - name: Get branch name
          id: branch-name
          uses: tj-actions/branch-names@v7

        - name:  Post Google Chat Message
          run: |
            curl --location --request POST '${{ secrets.GCHAT }}' \
            --header 'Content-Type: application/json' \
            --data-raw '{
                "cards": [
                    {
                      "header": {
                          "title": "Pull Request",
                          "subtitle": "Pull Request No: #${{ github.event.pull_request.number }}"
                      },
                      "sections": [
                          {
                              "widgets": [
                                  {
                                      "keyValue": {
                                          "topLabel": "Creator",
                                          "content": "${{ github.event.pull_request.user.login }}"
                                      },
                                    },
                                    {
                                      "keyValue": {
                                          "topLabel": "Repository Name",
                                          "content": "${{ github.event.repository.name }}"
                                      }
                                    },
                                    {
                                      "keyValue": {
                                          "topLabel": "Merge Branch",
                                          "content": "From ${{ steps.branch-name.outputs.current_branch }} branch To ${{ steps.branch-name.outputs.base_ref_branch }} branch"
                                      }
                                    },
                                    {
                                      "keyValue": {
                                          "topLabel": "PR Title",
                                          "content": "${{ github.event.pull_request.title }}"
                                      }
                                    },
                                    {
                                      "keyValue": {
                                          "topLabel": "Requested Reviwers",
                                          "content": "- ${{ join(github.event.pull_request.requested_reviewers.*.login) }}"
                                      }
                                    },
                                    {
                                      "keyValue": {
                                          "topLabel": "Assignees",
                                          "content": "- ${{ join(github.event.pull_request.assignees.*.login) }}"
                                      }
                                    },
                                    {
                                      "buttons": [
                                        {
                                          "textButton": {
                                            "text": "OPEN PR",
                                            "onClick": {
                                              "openLink": {
                                                "url": "${{ github.event.pull_request.html_url }}"
                                              }
                                            },
                                          },
                                        }
                                      ]
                                    },
                                  {
                                    "keyValue": {
                                        "topLabel": "You are welcome in advance, ${{ github.event.pull_request.user.login }}.",
                                        "content": "Thanks for your valuable Pull Request to ${{ steps.branch-name.outputs.base_ref_branch }} branch.\nYour dedication and expertise greatly contribute to our project's success.🫡"
                                    }
                                  },
                              ]
                          }
                      ],
                    }
                ]
            }'
      