name: First Work

on:
  - push

jobs:
  run-shell-commands:
    name: Run Shell Commands
    runs-on: ubuntu-latest
    steps:
      - name: echo a string
        run: echo "Hello World"
      - name: Multline Command
        run: |
          node -v
          npm -v
