name: First Work

on:
  - push

jobs:
  run-shell-commands:
    name: Run Shell Commands
    runs-on: ubuntu-latest
    steps:
      - name: echo a string
        run: echo "Hello World"
      - name: Multline Command
        run: |
          node -v
          npm -v
  run-parallel-jobs:
    name: Run Shell On Mac
    runs-on: macos-latest
    steps:
      - name: echo a string
        run: echo "Hello World from mac"
      - name: Multi-line Command
        run: |
          node -v
          npm -v

  dependent-jobs:
    name: Run on windows
    runs-on: windows-latest
    needs: [run-shell-commands]
    steps:
      - name: echo a string
        run: Write-Output "Windows string"
      - name: Error
        run: cause error
