name: First Work

on:
  push: 
    branches: [ master ]
  

jobs:
  merge_notifier:
    name: Merge Notification
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Logging Commits
        run: |
          echo "title=$(git log --format=%B -n 1 HEAD | head -n 1)" >> $GITHUB_OUTPUT

      - name:  Post Google Chat Message
        run: |
          curl --location --request POST '${{ secrets.GCHAT }}' \
          --header 'Content-Type: application/json' \
          --data-raw '{
              "cards": [
                  {
                    "header": {
                        "title": "Merge",
                        "subtitle": "Commit Message #$GITHUB_OUTPUT"
                    },
                    "sections": [
                        {
                            "widgets": [
                                {
                                    "keyValue": {
                                        "topLabel": "Creator",
                                        "content": "${{ github.event.pusher.name }}"
                                    },
                                  },
                                  {
                                    "keyValue": {
                                        "topLabel": "Repository Name",
                                        "content": "${{ github.event.repository.name }}"
                                    }
                                  },
                                  {
                                    "keyValue": {
                                        "topLabel": "Merged Branch",
                                        "content": "${{ github.ref_name }} branch"
                                    }
                                  },
                                {
                                  "keyValue": {
                                      "topLabel": "You are welcome in advance, ${{ github.event.pusher.name }}.",
                                      "content": "Grateful for successful feature push to ${{ github.ref_name }} branch.\nThanks to the collaborative effort and dedication of our team.🫡"
                                  }
                                },
                            ]
                        }
                    ],
                  }
              ]
          }'
    