name: First Work

on:
  - push

jobs:
  merge_notifier:
    name: Merge Notification
    runs-on: ubuntu-latest
    steps:
      - name: Get branch name
        id: branch-name
        uses: tj-actions/branch-names@v7

      - name:  Post Google Chat Message
        run: |
          curl --location --request POST '${{ secrets.GCHAT }}' \
          --header 'Content-Type: application/json' \
          --data-raw '{
              "cards": [
                  {
                    "header": {
                        "title": "Merge",
                        "subtitle": "subtitle"
                    },
                    "sections": [
                        {
                            "widgets": [
                                {
                                    "keyValue": {
                                        "topLabel": "Creator",
                                        "content": "${{ github.event.pusher.username.login }}"
                                    },
                                  },
                                  {
                                    "keyValue": {
                                        "topLabel": "Repository Name",
                                        "content": "${{ github.event.repository.name }}"
                                    }
                                  },
                                  {
                                    "keyValue": {
                                        "topLabel": "Merge Commit",
                                        "content": "${{ github.event.head_commit }}"
                                    }
                                  },
                                {
                                  "keyValue": {
                                      "topLabel": "You are welcome in advance, ${{ github.event.pusher.username.login }}.",
                                      "content": "Embrace the upcoming alterations in the NightWeb API APP with delight.\n Wishing you a productive and joyful development process!🫡"
                                  }
                                },
                            ]
                        }
                    ],
                  }
              ]
          }'
    